### ISSUE TITLE
Create separate issues for documenting each function

### ISSUE THREAD

**Issue by romainfrancois** [romainfrancois/dance#4]
Each function (used in the README) needs its own roxygen documentation, this issue is about creating another issue for each of the functions, `tango()`, `waltz()` ...

For example you can add some context in the issue: a reprex that you created by extracting some code from the README

See example issue #8 about `waltz()` and its pull request #7 by @cecilesauder. Feel free to add other issue and maybe reference them here. 

- [ ] `waltz()` issue #8 and pull request #7 
- [x] `choreography()` issue #22
- [ ] `polka()`  - issue #11 
- [ ] `tango()` - issue #12 
- [ ] `charleston()` - issue #13 
- [ ] `swing()` - issue #14
- [ ] `twist()` - issue #15
- [ ] `rumba()` - issue #16
- [ ] `zumba()` - issue #17
- [ ] `salsa()` - issue #18
- [ ] `samba()` - issue #19
- [ ] `chacha()` - issue #20
- [ ] `madison()` - issue #23
- [ ] `bolero()` - issue #24
- [ ] `mambo()` - issue #27

**Comment by dragosmg** [comment]
I would love to play this dance. 😄

**Comment by romainfrancois** [comment]
@dragosmg nice. You can get inspired from #8 and create some issues for other dances, e.g. `polka()`, `tango()` ... then I guess I can help in each of these issues if what the function does is not clear from what's on the README ...

**Comment by dragosmg** [comment]
New issues for documenting functions:
- [ ] `polka()`  - issue #11 
- [ ] `tango()` - issue #12 
- [ ] `charleston()` - issue #13 
- [ ] `swing()` - issue #14
- [ ] `twist()` - issue #15
- [ ] `rumba()` - issue #16
- [ ] `zumba()` - issue #17
- [ ] `salsa()` - issue #18
- [ ] `samba()` - issue #19
- [ ] `chacha()` - issue #20

**Comment by romainfrancois** [comment]
Thanks. I copied the bullet points in the main description of the issue so that we get that in the issue list

<img width="800" alt="image" src="https://user-images.githubusercontent.com/2625526/54067497-0c689a00-4241-11e9-9dcb-ab01bcd67efd.png">

**Comment by dragosmg** [comment]
@romainfrancois I'm trying to understand `mambo()`. What would be its `dplyr` equivalent?

**Comment by romainfrancois** [comment]
`mambo()` works together with `bolero()` to make something that can be compared to `filter_at() + all_vars()` or `filter_at() + `any_vars()`. 

Suppose you want to `filter()` the rows based on the same condition for multiple columns, in `dplyr` you can do e.g. 

``` r
library(dplyr, warn.conflicts = FALSE)

iris %>% 
  group_by(Species) %>% 
  filter_at(vars(starts_with("Sepal")), all_vars(. > 4))
#> # A tibble: 3 x 5
#> # Groups:   Species [1]
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#>          <dbl>       <dbl>        <dbl>       <dbl> <fct>  
#> 1          5.7         4.4          1.5         0.4 setosa 
#> 2          5.2         4.1          1.5         0.1 setosa 
#> 3          5.5         4.2          1.4         0.2 setosa
```

In `dance` you can combine `bolero()` (aka filter) with `mambo()` like this: 

``` r
library(dance)
library(tidyselect)
iris %>% 
  group_by(Species) %>% 
  bolero(mambo(~. > 4, starts_with("Sepal")))
#> # A tibble: 3 x 5
#> # Groups:   Species [3]
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#>          <dbl>       <dbl>        <dbl>       <dbl> <fct>  
#> 1          5.7         4.4          1.5         0.4 setosa 
#> 2          5.2         4.1          1.5         0.1 setosa 
#> 3          5.5         4.2          1.4         0.2 setosa
```

The advantage is that you may use `mambo()` as well as some other predicates if you like: 

``` r
library(dance)
library(tidyselect)
iris %>% 
  group_by(Species) %>% 
  bolero(
    mambo(~. > 4, starts_with("Sepal")), 
    ~Petal.Width < .3
  )
#> # A tibble: 2 x 5
#> # Groups:   Species [3]
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#>          <dbl>       <dbl>        <dbl>       <dbl> <fct>  
#> 1          5.2         4.1          1.5         0.1 setosa 
#> 2          5.5         4.2          1.4         0.2 setosa
```

You can't really do that with `filter_at()` you'd have to pipe into an additional `filter()`. So essentially the job of `mambo()` is to generate a formula that `bolero()` can use. 

`mambo(~. > 4, starts_with("Sepal"))` generates something like (not quite) `~ Sepal.Width > 4 & Sepal.Length > 4` so the repress above is equivalent to: 

``` r
library(dance)

iris %>% 
  group_by(Species) %>% 
  bolero(
    ~Sepal.Width > 4 & Sepal.Length > 4, 
    ~Petal.Width < .3
  )
#> # A tibble: 2 x 5
#> # Groups:   Species [3]
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#>          <dbl>       <dbl>        <dbl>       <dbl> <fct>  
#> 1          5.2         4.1          1.5         0.1 setosa 
#> 2          5.5         4.2          1.4         0.2 setosa
```

<sup>Created on 2019-03-09 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by romainfrancois** [comment]
Some differences with how `filter_at()` organizes the arguments, `mambo()` takes first a function (or a formula that uses `.`) and then uses the `...` for the tidy selection of variables and an optional `.op` argument for how to join the predicates (but most of the time `.op = and`. the default makes the most sense.

**Comment by dragosmg** [comment]
Cool. Thanks. Much clearer now. I think all functions from the  `README.Rmd` are covered by individual issues.

**Comment by romainfrancois** [comment]
Thanks, I'm moving the comment about `mambo()` in the dedicated issue.
